<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="55" width="57" alt="3WA Restaurant">Restaurant - Made In America !
        </a>
    </h1>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="link-list">
        <?php if(count($_SESSION) > 0) :?>
            <a href='<?= $requestUrl ?>/reservation'><button>Réserver</button></a>
            <a href='<?= $requestUrl ?>/order'><button>Commander</button></a>

           <a href="" id="" <i class="fa fa-shopping-cart" aria-hidden="true"></i>

            <div>

                <a href='<?= $requestUrl ?>/deconnect'><button>Deconnexion</button></a>
                <p>Bonjour <?= $_SESSION['nom'] ?></p>
            </div>
        <?php else : ?>
            <a href='<?= $requestUrl ?>/signup'><button>Créer un compte</button></a>
            <a href='<?= $requestUrl ?>/login/'><button>Connexion</button></a>
        <?php endif ?>
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>