<h1><i class="fa fa-shopping-cart" aria-hidden="true"></i>Passer une commande</h1>
<form action="" method="post">
    <fieldset>
        <legend>Ajouter un article</legend>
        <label for="article">Nom :</label>
       <select name="article" id="mealSelector">
        <?php foreach($meals as $meal): ?>
           <option value="<?= $meal["id"] ?>">
           <?= $meal["name"] ?>
            </option>
           <?php endforeach; ?>
       </select>
        <br />
        <div id="choice"></div>
        <label for="quantite" id="quantite">quantité :</label>
        <input type="number" id="quantity" name="quantite" value="1" min="1" max="99" >
        <br />
        <input type="button" value="ajouter" id="add">
    </fieldset>
    <fieldset id="Récapitulatif">
        <legend>Récapitulatif de la commande</legend>
        <div id="liste"></div>
    </fieldset>
    <button id="valider" type="button">valider la commande</button>
</form>
